[package]
name = "mock-runtime"
description = "A solochain runtime template built with Substrate, part of Polkadot Sdk."
version = "0.1.0"
license = "Unlicense"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
publish = false

[dependencies]
log = { workspace = true }
codec = { workspace = true }
scale-info = { workspace = true }
polkadot-sdk = { workspace = true, features = ["pallet-balances", "pallet-sudo", "pallet-timestamp", "pallet-transaction-payment", "pallet-transaction-payment-rpc-runtime-api", "runtime", "sp-api", "sp-runtime", "sp-core", "sp-api", "sp-genesis-builder", "sp-inherents", "sp-block-builder", "sp-std", "sp-offchain", "sp-session", "frame-system-rpc-runtime-api", "frame-system", "frame-support"] }
serde_json = { workspace = true, default-features = false, features = ["alloc"] }
serde = { workspace = true, features = ["derive"] }

[build-dependencies]
polkadot-sdk = { optional = true, workspace = true, features = ["substrate-wasm-builder"] }

[features]
default = ["std"]
std = [
	"codec/std",
	"polkadot-sdk/std",
	"scale-info/std",
	"serde_json/std",
	"log/std",
	"serde/std",
]
